name: Python package

on:
  push:
    branches:
      - '*'  # Ou qualquer outro branch que você deseje
  pull_request:
    branches:
      - main  # Ou qualquer outro branch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.14]  # Verifique versões mais recentes como 3.11 também

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
